<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppMvp.Application\AppMvp.ApplicationCore.csproj" />
    <ProjectReference Include="..\AppMvp.Domain\AppMvp.Domain.csproj" />
  </ItemGroup>

</Project>
